name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    if: github.repository == 'akka/akka-http-quickstart-java.g8'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: sbt & Paradox
        run: sbt test docs/paradox
