name: Build and test

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"

permissions:
  contents: read

jobs:
  build-test:
    if: github.repository == 'akka/akka-http-quickstart-java.g8'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: sbt & Paradox
        run: sbt test docs/paradox

      - name: Maven
        run: |-
          sbt new file://$PWD --name=hello-world --force && pushd hello-world &&  mvn test

      - name: Gradle
        run: |-
          sbt new file://$PWD --name=hello-world --force && pushd hello-world &&  ./gradlew --console=plain build
